import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :agentic_ui, AgenticUiWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# SSL is terminated at the Kubernetes Ingress/LoadBalancer, not in Phoenix.
# The app runs plain HTTP inside the cluster.
# If deploying without K8s and needing SSL at the app level, uncomment:
# config :agentic_ui, AgenticUiWeb.Endpoint,
#   force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
